package com.example.oAuth2Demo;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

@Configuration
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    public void configure (HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .antMatcher("/**").authorizeRequests()
                .antMatchers("/").permitAll()
                .anyRequest().authenticated()
                .and()
                .oauth2Login();
    }
}


/**
 *  1. CV -> generated by Java. generated by Java. MS Word.
 *  Apache POI -> Microsoft office.
 *
 *  MVP -< Minimal Viable Product
 *
 *  2. Intellij plugin.
 *
 *
 *
 *
 */
